"""The shared main.py template.

The wizard and Set as Main Form write the same file. Kept as two literals they
drifted — one emitted two blank lines after the import (tripping I001), the
other one — so re-pointing the main form silently rewrote main.py.
"""
from __future__ import annotations

import inspect

import app as app_mod
from utils import starter_templates
from widgets import project_wizard as pw_mod

FORM = "MainForm"

# The pre-fix template, kept as a literal so the regression it caused stays
# covered rather than becoming folklore.
TWO_BLANK_LINES = (
    f"# Generated by IDOL Designer\n"
    f"from {FORM} import {FORM}\n\n\n"
    f'if __name__ == "__main__":\n'
    f"    app = {FORM}()\n"
    f"    app.mainloop()\n"
)


def test_the_old_template_really_did_trip_isort(lint_source):
    assert "I001" in lint_source(TWO_BLANK_LINES, "I", "old_main.py")


def test_template_is_lint_clean(lint_source):
    assert lint_source(starter_templates.idol_main_py(FORM),
                       "I,E,W,F", "new_main.py") == []


def test_template_survives_a_broad_rule_set(lint_source):
    """Including the rules ruff 0.16 would have added by default."""
    assert lint_source(starter_templates.idol_main_py(FORM),
                       "I,E,W,F,BLE,S,EXE,UP", "broad_main.py") == []


def test_template_compiles():
    compile(starter_templates.idol_main_py(FORM), "main.py", "exec")


def test_marker_round_trips():
    assert starter_templates.is_idol_main_py(starter_templates.idol_main_py(FORM))


def test_user_authored_main_is_not_claimed():
    """Set as Main Form prompts before overwriting a main.py it did not write."""
    assert not starter_templates.is_idol_main_py("print('hi')\n")


def test_both_writers_emit_identical_content():
    """The drift itself: creating a project then Set as Main Form rewrote the
    same file with different whitespace."""
    assert app_mod.IDOL._idol_main_py_content(None, FORM) == \
        starter_templates.idol_main_py(FORM)


def test_neither_call_site_carries_its_own_literal():
    """Structural — the point of the shared module is that a copy cannot drift
    back in, and only source inspection catches someone re-inlining one."""
    wiz = inspect.getsource(pw_mod.ProjectWizard._write_starter_files)
    app_side = inspect.getsource(app_mod.IDOL._idol_main_py_content)
    assert starter_templates.IDOL_MAIN_MARKER not in wiz
    assert starter_templates.IDOL_MAIN_MARKER not in app_side
    assert "starter_templates.idol_main_py" in wiz


def test_non_gui_starter_is_clean(lint_source):
    """The wizard's other branch — no import block, already fine, left alone."""
    src = ('def main():\n    print("Hello, World!")\n\n\n'
           'if __name__ == "__main__":\n    main()\n')
    assert lint_source(src, "I,E,W,F", "nongui_main.py") == []
