[editor]
bg = "#1e1f29"
fg = "#b0bec5"
select_bg = "#3a4055"
select_fg = "#b0bec5"
inactive_select_bg = "#3a4055"
caret = "#b0bec5"
caret_width = 1
border_width = 0
focus_border_width = 0

[general]
comment = "#586e75"
error = "#d33682"
escape = "#6c71c4"
keyword = "#859900"
name = "#268bd2"
string = "#2aa198"
punctuation = "#93a1a1"

[keyword]
constant = "#b58900"
declaration = "#cb4b16"
namespace = "#268bd2"
pseudo = "#d33682"
reserved = "#859900"
type = "#268bd2"

[name]
attr = "#268bd2"
builtin = "#6c71c4"
builtin_pseudo = "#cb4b16"
class = "#268bd2"
class_variable = "#268bd2"
constant = "#d33682"
decorator = "#6c71c4"
entity = "#268bd2"
exception = "#d33682"
function = "#268bd2"
global_variable = "#268bd2"
instance_variable = "#268bd2"
label = "#268bd2"
magic_function = "#6c71c4"
magic_variable = "#268bd2"
namespace = "#b0bec5"
tag = "#859900"
variable = "#859900"

[operator]
symbol = "#859900"
word = "#859900"

[string]
affix = "#2aa198"
char = "#2aa198"
delimeter = "#2aa198"
doc = "#2aa198"
double = "#2aa198"
escape = "#2aa198"
heredoc = "#2aa198"
interpol = "#2aa198"
regex = "#2aa198"
single = "#2aa198"
symbol = "#2aa198"

[number]
binary = "#b58900"
float = "#b58900"
hex = "#b58900"
integer = "#b58900"
long = "#b58900"
octal = "#b58900"

[comment]
hashbang = "#586e75"
multiline = "#586e75"
preproc = "#d33682"
preprocfile = "#2aa198"
single = "#586e75"
special = "#586e75"

