[editor]
bg = "#282923"
fg = "#e6e6e0"
select_bg = "#92264b"
select_fg = "#e6e6e0"
inactive_select_bg = "#92264b"
caret = "#e6e6e0"
caret_width = 1
border_width = 0
focus_border_width = 0

[general]
comment = "#66d6ed"
error = "#f62471"
escape = "#e6e6e0"
keyword = "#f62471"
name = "#467e86"
string = "#916ed2"
punctuation = "#f62471"

[keyword]
constant = "#4c4b38"
declaration = "#f62471"
namespace = "#f62471"
pseudo = "#4c4b38"
reserved = "#f62471"
type = "#f62471"

[name]
attr = "#467e86"
builtin = "#f59221"
builtin_pseudo = "#7a7545"
class = "#467e86"
class_variable = "#467e86"
constant = "#e6e6e0"
decorator = "#f59221"
entity = "#467e86"
exception = "#f59221"
function = "#467e86"
global_variable = "#467e86"
instance_variable = "#467e86"
label = "#467e86"
magic_function = "#f59221"
magic_variable = "#467e86"
namespace = "#e6e6e0"
tag = "#f62471"
variable = "#f62471"

[operator]
symbol = "#d6cb6c"
word = "#f62471"

[string]
affix = "#916ed2"
char = "#916ed2"
delimeter = "#916ed2"
doc = "#916ed2"
double = "#916ed2"
escape = "#916ed2"
heredoc = "#916ed2"
interpol = "#916ed2"
regex = "#916ed2"
single = "#916ed2"
symbol = "#916ed2"

[number]
binary = "#4c4b38"
float = "#4c4b38"
hex = "#4c4b38"
integer = "#4c4b38"
long = "#4c4b38"
octal = "#4c4b38"

[comment]
hashbang = "#66d6ed"
multiline = "#66d6ed"
preproc = "#f62471"
preprocfile = "#916ed2"
single = "#66d6ed"
special = "#66d6ed"

