"""Git diagnostic utilities — file classification, issue detection, health checks."""
from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable


# ── File classification ───────────────────────────────────────────────────────

@dataclass
class FileInfo:
    category: str        # "venv" | "secret" | "build" | "os" | "ide" | "code" | "data" | "unknown"
    label: str           # short human label e.g. "Virtual Environment"
    explanation: str     # one-sentence why git cares
    severity: str        # "high" | "medium" | "low"


_VENV_PATTERNS = [
    r"^(bin|Scripts)/(activate|python[\d.]*|pip[\d.]*|easy_install.*|wheel.*|f2py.*)$",
    r"^(bin|Scripts)/",
    r"^lib/python[\d.]+/",
    r"^lib64/",
    r"^include/",
    r"^pyvenv\.cfg$",
    r"^(Lib|lib)/site-packages/",
    r"\.(dist-info|egg-info)/",
    r"^(Activate\.ps1|activate\.csh|activate\.fish)$",
    r"^(INSTALLER|METADATA|RECORD|REQUESTED|WHEEL|top_level\.txt)$",
    r"^__pycache__/",
    r"\.py[cod]$",
    r"\$py\.class$",
]

_SECRET_PATTERNS = [
    r"\.env$",
    r"\.env\.",
    r"secrets?\.(json|yaml|yml|toml|cfg|ini)$",
    r"credentials?\.(json|yaml|yml|toml|cfg|ini)$",
    r"api[_-]?keys?\.(json|yaml|yml|toml|cfg|ini)$",
    r"config\.(json|yaml|yml)$",
    r"(private|id)_rsa$",
    r"\.pem$",
    r"\.p12$",
    r"\.key$",
    r"\.pfx$",
    r"service.account",
]

_BUILD_PATTERNS = [
    r"^dist/",
    r"^build/",
    r"^out/",
    r"^target/",
    r"\.egg-info/",
    r"^\.eggs/",
    r"^htmlcov/",
    r"^\.pytest_cache/",
    r"\.coverage$",
    r"\.pyc$",
]

_OS_PATTERNS = [
    r"^\.DS_Store$",
    r"^Thumbs\.db$",
    r"^desktop\.ini$",
    r"^\._",
    r"^\.Spotlight-",
    r"^\.Trashes$",
]

_IDE_PATTERNS = [
    r"^\.vscode/",
    r"^\.idea/",
    r"\.swp$",
    r"\.swo$",
    r"~$",
]

_VENV_RE  = [re.compile(p) for p in _VENV_PATTERNS]
_SECRET_RE = [re.compile(p, re.IGNORECASE) for p in _SECRET_PATTERNS]
_BUILD_RE = [re.compile(p) for p in _BUILD_PATTERNS]
_OS_RE    = [re.compile(p) for p in _OS_PATTERNS]
_IDE_RE   = [re.compile(p) for p in _IDE_PATTERNS]


def classify_file(path: str) -> FileInfo:
    """Return a FileInfo describing what this file is and why git cares."""
    name = os.path.basename(path)
    # Normalize to forward slashes for pattern matching
    p = path.replace("\\", "/")

    for pattern in _VENV_RE:
        if pattern.search(p) or pattern.search(name):
            return FileInfo(
                category="venv",
                label="Virtual Environment",
                explanation="Part of a Python virtual environment — should never be committed. Add venv/ to .gitignore.",
                severity="high",
            )

    for pattern in _SECRET_RE:
        if pattern.search(p) or pattern.search(name):
            return FileInfo(
                category="secret",
                label="Potential Secret",
                explanation="May contain API keys or credentials — committing this could expose sensitive data publicly.",
                severity="high",
            )

    for pattern in _BUILD_RE:
        if pattern.search(p) or pattern.search(name):
            return FileInfo(
                category="build",
                label="Build Artifact",
                explanation="Generated by the build process — can always be recreated, no need to track in git.",
                severity="medium",
            )

    for pattern in _OS_RE:
        if pattern.search(p) or pattern.search(name):
            return FileInfo(
                category="os",
                label="OS Metadata",
                explanation="Created automatically by your operating system — not part of your project.",
                severity="low",
            )

    for pattern in _IDE_RE:
        if pattern.search(p) or pattern.search(name):
            return FileInfo(
                category="ide",
                label="Editor Config",
                explanation="IDE or editor settings — usually personal and not useful to other contributors.",
                severity="low",
            )

    return FileInfo(
        category="code",
        label="Project File",
        explanation="Part of your project — consider whether this should be tracked in git.",
        severity="low",
    )


# ── Issue detection ───────────────────────────────────────────────────────────

@dataclass
class Issue:
    key: str             # unique identifier
    title: str
    what: str            # "What happened"
    why: str             # "Why it matters"
    how: str             # "How to fix it"
    severity: str        # "high" | "medium" | "low"
    fix_label: str       # button label e.g. "Create .gitignore"
    fix_fn: Callable | None = field(default=None, repr=False)
    count: int = 0       # number of affected files


def analyze_files(unstaged: dict[str, str],
                  fix_fns: dict[str, Callable] | None = None) -> list[Issue]:
    """Analyze unstaged files and return a list of detected Issues."""
    fix_fns = fix_fns or {}
    counts: dict[str, int] = {}
    for path in unstaged:
        info = classify_file(path)
        counts[info.category] = counts.get(info.category, 0) + 1

    issues: list[Issue] = []

    if counts.get("venv", 0) > 0:
        issues.append(Issue(
            key="venv",
            title="Virtual Environment Detected",
            what=f"{counts['venv']} virtual environment files are untracked.",
            why="Virtual environments can contain hundreds of files and are specific to your machine. "
                "Committing them bloats the repo and causes conflicts for other contributors.",
            how="Add your venv folder to .gitignore (e.g. venv/, .venv/, bin/, lib/). "
                "If already committed, run: git rm -r --cached <venv-folder>",
            severity="high",
            fix_label="Create .gitignore",
            fix_fn=fix_fns.get("create_gitignore"),
            count=counts["venv"],
        ))

    if counts.get("secret", 0) > 0:
        issues.append(Issue(
            key="secret",
            title="Potential Secrets Detected",
            what=f"{counts['secret']} file(s) may contain sensitive data.",
            why="API keys, passwords, and credentials committed to git are permanently in the history "
                "— even if deleted later. This can lead to account compromise or data breaches.",
            how="Add these files to .gitignore immediately. If already committed, rotate any exposed "
                "keys and use git filter-branch or BFG Repo Cleaner to purge them from history.",
            severity="high",
            fix_label="Create .gitignore",
            fix_fn=fix_fns.get("create_gitignore"),
            count=counts["secret"],
        ))

    if counts.get("build", 0) > 0:
        issues.append(Issue(
            key="build",
            title="Build Artifacts Detected",
            what=f"{counts['build']} build artifact(s) are untracked.",
            why="Build outputs like dist/, __pycache__/, and .pyc files are generated automatically "
                "and differ per machine. Tracking them adds noise to your git history.",
            how="Add build output folders to .gitignore. They will be recreated when needed.",
            severity="medium",
            fix_label="Create .gitignore",
            fix_fn=fix_fns.get("create_gitignore"),
            count=counts["build"],
        ))

    if counts.get("os", 0) > 0:
        issues.append(Issue(
            key="os",
            title="OS Metadata Files Detected",
            what=f"{counts['os']} OS-generated file(s) are untracked (.DS_Store, Thumbs.db, etc.).",
            why="These files are created by your operating system and are meaningless to other "
                "contributors on different platforms.",
            how="Add .DS_Store and Thumbs.db to .gitignore.",
            severity="low",
            fix_label="Create .gitignore",
            fix_fn=fix_fns.get("create_gitignore"),
            count=counts["os"],
        ))

    return issues


# ── Health checks ─────────────────────────────────────────────────────────────

@dataclass
class HealthCheck:
    key: str
    label: str
    passed: bool
    detail: str          # short explanation of current state
    fix_label: str | None = None
    fix_fn: Callable | None = field(default=None, repr=False)


def health_checks(
    repo_root: str,
    staged: dict[str, str],
    unstaged: dict[str, str],
    fix_fns: dict[str, Callable] | None = None,
) -> list[HealthCheck]:
    """Return a list of HealthCheck results for the repo's current state."""
    fix_fns = fix_fns or {}
    checks: list[HealthCheck] = []

    # .gitignore exists
    has_gitignore = os.path.exists(os.path.join(repo_root, ".gitignore"))
    checks.append(HealthCheck(
        key="gitignore",
        label=".gitignore exists",
        passed=has_gitignore,
        detail="Found" if has_gitignore else "No .gitignore — untracked files won't be filtered",
        fix_label=None if has_gitignore else "Create .gitignore",
        fix_fn=None if has_gitignore else fix_fns.get("create_gitignore"),
    ))

    # No venv files untracked
    venv_count = sum(1 for p in unstaged if classify_file(p).category == "venv")
    checks.append(HealthCheck(
        key="no_venv",
        label="No venv files untracked",
        passed=venv_count == 0,
        detail=f"{venv_count} venv file(s) untracked" if venv_count else "Clean",
        fix_label="Create .gitignore" if venv_count else None,
        fix_fn=fix_fns.get("create_gitignore") if venv_count else None,
    ))

    # No potential secrets untracked or staged
    all_files = {**unstaged, **staged}
    secret_count = sum(1 for p in all_files if classify_file(p).category == "secret")
    checks.append(HealthCheck(
        key="no_secrets",
        label="No potential secrets tracked",
        passed=secret_count == 0,
        detail=f"{secret_count} file(s) may contain secrets" if secret_count else "Clean",
        fix_label="Create .gitignore" if secret_count else None,
        fix_fn=fix_fns.get("create_gitignore") if secret_count else None,
    ))

    # No build artifacts staged
    build_staged = sum(1 for p in staged if classify_file(p).category == "build")
    checks.append(HealthCheck(
        key="no_build_staged",
        label="No build artifacts staged",
        passed=build_staged == 0,
        detail=f"{build_staged} build artifact(s) staged" if build_staged else "Clean",
    ))

    # Nothing staged that looks like OS metadata
    os_staged = sum(1 for p in staged if classify_file(p).category == "os")
    checks.append(HealthCheck(
        key="no_os_staged",
        label="No OS metadata staged",
        passed=os_staged == 0,
        detail=f"{os_staged} OS metadata file(s) staged" if os_staged else "Clean",
    ))

    return checks
