"""Starter-file templates for generated projects.

The GUI entry point is written from two places — `widgets/project_wizard.py`
when a project is created, and `app.py`'s Set as Main Form when the main form
changes — and they are the *same file* on disk. Kept as two literals they
drifted: the wizard emitted two blank lines after the import and Set as Main
Form emitted one, so merely re-pointing the main form rewrote main.py with
different whitespace, and the wizard's copy tripped `I001` on a project the
user had just created.

One definition, both callers. Living in `utils/` is what lets both reach it —
`widgets/` may import from `utils/`, never from `app.py`.
"""
from __future__ import annotations

#: Marker identifying a main.py IDOL generated, so Set as Main Form knows
#: whether overwriting needs a confirmation prompt. Part of the template, so it
#: cannot drift away from what `is_idol_main_py` looks for.
IDOL_MAIN_MARKER = "# Generated by IDOL Designer"


def idol_main_py(form_name: str) -> str:
    """Entry point for a Tkinter GUI project whose main form is *form_name*.

    Exactly one blank line between the import and the `if __name__` guard:
    isort wants a single blank after an import block when what follows is not a
    `def` or `class`, and two made generated projects flag themselves.
    """
    return (
        f"{IDOL_MAIN_MARKER}\n"
        f"from {form_name} import {form_name}\n"
        f"\n"
        f'if __name__ == "__main__":\n'
        f"    app = {form_name}()\n"
        f"    app.mainloop()\n"
    )


def is_idol_main_py(content: str) -> bool:
    """True when *content* is a main.py IDOL generated (vs. user-authored)."""
    return IDOL_MAIN_MARKER in content
