from __future__ import annotations

"""
Non-visual component type registry for the IDOL Designer component tray.

Each entry in COMPONENT_REGISTRY defines how a component looks in the palette,
what properties it exposes in the Properties panel, what handler methods it
generates, and how its __init__ initialization is emitted in codegen.
"""

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class PropDef:
    """Definition of one property row shown in the Properties panel for a component."""
    key:         str   # dict key in ComponentDescriptor.props
    label:       str   # display label in Properties tab
    kind:        str   # "int" | "bool" | "str" | "readonly"
    default:     Any   # value used when component is first created
    description: str   # hint bar text on hover


@dataclass(frozen=True)
class ComponentHandlerDef:
    """Definition of one handler method generated for a component."""
    id:            str   # short id used internally, e.g. "tick"
    label:         str   # method name suffix, e.g. "_tick"  (prepended with _{comp_id})
    description:   str   # hint bar text in the Handlers tab
    has_connector: bool  # True → show ⚡ connector button (can wire to a widget event)
    default_body:  str   # body used on first codegen; "" = use fixed template


@dataclass(frozen=True)
class ComponentDef:
    """Full definition of one component type."""
    type_key:        str                         # "Timer"
    label:           str                         # palette display name
    icon:            str                         # Unicode glyph shown in tray chip
    description:     str                         # palette tooltip / hint bar
    default_name:    str                         # auto-numbered base, e.g. "timer" → "timer1"
    prop_defs:       tuple[PropDef, ...]
    handler_defs:    tuple[ComponentHandlerDef, ...]
    codegen_imports: list[str] = field(default_factory=list)  # extra import lines ([] for Timer)


# ── Component registry ────────────────────────────────────────────────────────

COMPONENT_REGISTRY: dict[str, ComponentDef] = {

    "Timer": ComponentDef(
        type_key="Timer",
        label="Timer",
        icon="⏱",
        description="Periodic callback using tkinter's after() — runs on the main thread, no locks needed",
        default_name="timer",
        codegen_imports=[],
        prop_defs=(
            PropDef(
                key="interval",
                label="Interval (ms)",
                kind="int",
                default=1000,
                description="Milliseconds between ticks (1–65535). Set Enabled to False to start paused.",
            ),
            PropDef(
                key="enabled",
                label="Enabled",
                kind="bool",
                default=True,
                description="If True, timer starts automatically when the form loads.",
            ),
        ),
        handler_defs=(
            ComponentHandlerDef(
                id="tick",
                label="_tick",
                description="Fires every Interval ms. Add your repeating logic here.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="start",
                label="_start",
                description="Starts or resumes the timer. Wire to a button to let the user control it.",
                has_connector=True,
                default_body="",  # fixed template generated by codegen
            ),
            ComponentHandlerDef(
                id="stop",
                label="_stop",
                description="Stops the timer. Wire to a button to let the user control it.",
                has_connector=True,
                default_body="",  # fixed template generated by codegen
            ),
        ),
    ),

}


# ── Helpers ───────────────────────────────────────────────────────────────────

def all_component_types() -> list[str]:
    """Return all registered component type keys in display order."""
    return list(COMPONENT_REGISTRY.keys())


def get_component_def(type_key: str) -> ComponentDef | None:
    return COMPONENT_REGISTRY.get(type_key)


def default_props(type_key: str) -> dict[str, Any]:
    """Return a fresh props dict with all defaults for a component type."""
    cdef = COMPONENT_REGISTRY.get(type_key)
    if not cdef:
        return {}
    return {p.key: p.default for p in cdef.prop_defs}
