from __future__ import annotations

"""
Non-visual component type registry for the IDOL Designer component tray.

Each entry in COMPONENT_REGISTRY defines how a component looks in the palette,
what properties it exposes in the Properties panel, what handler methods it
generates, and how its __init__ initialization is emitted in codegen.
"""

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class PropDef:
    """Definition of one property row shown in the Properties panel for a component."""
    key:         str   # dict key in ComponentDescriptor.props
    label:       str   # display label in Properties tab
    kind:        str   # "int" | "bool" | "str" | "readonly"
    default:     Any   # value used when component is first created
    description: str   # hint bar text on hover


@dataclass(frozen=True)
class ComponentHandlerDef:
    """Definition of one handler method generated for a component."""
    id:                 str            # short id used internally, e.g. "tick"
    label:              str            # method name suffix, e.g. "_tick"  (prepended with _{comp_id})
    description:        str            # hint bar text in the Handlers tab
    has_connector:      bool           # True → show ⚡ connector button (can wire to a widget event)
    default_body:       str            # body used on first codegen; "" = use fixed template
    applies_to_widgets: tuple[str, ...] = ()  # empty = all widget types; non-empty = allowlist
    applies_to_modes:   tuple[str, ...] = ()  # empty = all socket modes; ("server",)/("client",) = restricted


@dataclass(frozen=True)
class ComponentDef:
    """Full definition of one component type."""
    type_key:        str                         # "Timer"
    label:           str                         # palette display name
    icon:            str                         # Unicode glyph shown in tray chip
    description:     str                         # palette tooltip / hint bar
    default_name:    str                         # auto-numbered base, e.g. "timer" → "timer1"
    prop_defs:       tuple[PropDef, ...]
    handler_defs:    tuple[ComponentHandlerDef, ...]
    codegen_imports: list[str] = field(default_factory=list)  # extra import lines ([] for Timer)


# ── Component registry ────────────────────────────────────────────────────────

COMPONENT_REGISTRY: dict[str, ComponentDef] = {

    "Timer": ComponentDef(
        type_key="Timer",
        label="Timer",
        icon="⏱",
        description="Periodic callback using tkinter's after() — runs on the main thread, no locks needed",
        default_name="timer",
        codegen_imports=[],
        prop_defs=(
            PropDef(
                key="interval",
                label="Interval (ms)",
                kind="int",
                default=1000,
                description="Milliseconds between ticks (1–65535). Set Enabled to False to start paused.",
            ),
            PropDef(
                key="enabled",
                label="Enabled",
                kind="bool",
                default=True,
                description="If True, timer starts automatically when the form loads.",
            ),
        ),
        handler_defs=(
            ComponentHandlerDef(
                id="tick",
                label="_tick",
                description="Fires every Interval ms. Add your repeating logic here.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="start",
                label="_start",
                description="Starts or resumes the timer. Wire to a button to let the user control it.",
                has_connector=True,
                default_body="",  # fixed template generated by codegen
            ),
            ComponentHandlerDef(
                id="stop",
                label="_stop",
                description="Stops the timer. Wire to a button to let the user control it.",
                has_connector=True,
                default_body="",  # fixed template generated by codegen
            ),
        ),
    ),

    "CommonDialog": ComponentDef(
        type_key="CommonDialog",
        label="CommonDialog",
        icon="📁",
        description="Open/Save/Dir/Color/Input dialogs — wire handlers to buttons for file, color, and simple input dialogs",
        default_name="cd",
        codegen_imports=["from tkinter import filedialog", "from tkinter import colorchooser", "from tkinter import simpledialog"],
        prop_defs=(
            PropDef(
                key="init_dir",
                label="Initial Dir",
                kind="str",
                default="",
                description="Starting folder when the dialog opens. Leave blank for the OS default.",
            ),
            PropDef(
                key="filter",
                label="Filter",
                kind="str",
                default="All Files (*.*)|*.*",
                description='Pipe-separated pairs: "Text Files (*.txt)|*.txt|All Files (*.*)|*.*"',
            ),
            PropDef(
                key="default_ext",
                label="Default Ext",
                kind="str",
                default="",
                description="Extension appended when the user types a filename with no extension (e.g. .txt).",
            ),
            PropDef(
                key="prompt",
                label="Prompt",
                kind="str",
                default="Enter a value:",
                description="Question shown inside the input dialog (used by _ask_input).",
            ),
            PropDef(
                key="default_value",
                label="Default Value",
                kind="str",
                default="",
                description="Pre-filled value in the input dialog (used by _ask_input).",
            ),
        ),
        handler_defs=(
            ComponentHandlerDef(
                id="show_open",
                label="_show_open",
                description="Opens an Open-File dialog. Wire to a Button or Label click.",
                has_connector=True,
                default_body="",
                applies_to_widgets=("Button", "Label"),
            ),
            ComponentHandlerDef(
                id="show_save",
                label="_show_save",
                description="Opens a Save-File dialog. Wire to a Button or Label click.",
                has_connector=True,
                default_body="",
                applies_to_widgets=("Button", "Label"),
            ),
            ComponentHandlerDef(
                id="choose_dir",
                label="_choose_dir",
                description="Opens a Choose-Directory dialog. Wire to a Button or Label click.",
                has_connector=True,
                default_body="",
                applies_to_widgets=("Button", "Label"),
            ),
            ComponentHandlerDef(
                id="ask_open_file",
                label="_ask_open_file",
                description="Opens a file for reading and populates a target widget. Wire to a Button or Label click.",
                has_connector=True,
                default_body="",
                applies_to_widgets=("Button", "Label"),
            ),
            ComponentHandlerDef(
                id="ask_save_file",
                label="_ask_save_file",
                description="Opens a file for writing from a target widget. Wire to a Button or Label click.",
                has_connector=True,
                default_body="",
                applies_to_widgets=("Button", "Label"),
            ),
            ComponentHandlerDef(
                id="choose_color",
                label="_choose_color",
                description="Opens a color-picker dialog. Wire to a Button or Label click.",
                has_connector=True,
                default_body="",
                applies_to_widgets=("Button", "Label"),
            ),
            ComponentHandlerDef(
                id="on_file_selected",
                label="_on_file_selected",
                description="Called after the user picks a file. Read self._cd1_filename here.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="on_file_opened",
                label="_on_file_opened",
                description="Called after file content is read when no target widget is wired. Use self._cd1_file_content.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="on_color_selected",
                label="_on_color_selected",
                description="Called after the user picks a color. Read self._cd1_color_hex and self._cd1_color_rgb.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="ask_input",
                label="_ask_input",
                description="Opens a simple input dialog (string/integer/float). Choose type in the connector. Wire to a Button or Label click.",
                has_connector=True,
                default_body="",
                applies_to_widgets=("Button", "Label"),
            ),
            ComponentHandlerDef(
                id="on_input_result",
                label="_on_input_result",
                description="Called after the user enters a value. Read self._cd1_result here.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="messagebox",
                label="_messagebox",
                description="Shows a question dialog (askyesno, askokcancel, etc.). Wire to a Button or Label click.",
                has_connector=True,
                default_body="",
                applies_to_widgets=("Button", "Label"),
            ),
            ComponentHandlerDef(
                id="on_messagebox_result",
                label="_on_messagebox_result",
                description="Called after the user answers the question dialog. Read self._cd1_result here.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
        ),
    ),

    "Image": ComponentDef(
        type_key="Image",
        label="Image",
        icon="🖼",
        description="Named image reference(s) loaded in __init__ — single file becomes self.name, multiple become self.name = {key: PhotoImage}",
        default_name="img",
        codegen_imports=[],   # PIL import handled by _has_images in codegen
        prop_defs=(
            PropDef(
                key="paths",
                label="images",
                kind="image_list",
                default=[],
                description="Image file(s) — click to pick one or more files. Single file → self.name, multiple → self.name = {stem: PhotoImage, ...}",
            ),
            PropDef(
                key="parent",
                label="parent",
                kind="canvas_ref",
                default="",
                description="Canvas widget this image set belongs to. When set, these images appear in the canvas editor for that widget.",
            ),
        ),
        handler_defs=(
            ComponentHandlerDef(
                id="canvas_button",
                label="_canvas_button",
                description="Place an image button on a Canvas widget — click ⚡ to configure position, images, and tag name",
                has_connector=True,
                default_body="",
                applies_to_widgets=("Canvas",),
            ),
        ),
    ),

    "Socket": ComponentDef(
        type_key="Socket",
        label="Socket",
        icon="⬡",
        description="TCP socket — Server listens for connections, Client connects to a server. Runs on daemon threads, callbacks fire on the main thread.",
        default_name="sock",
        codegen_imports=["import socket", "import threading"],
        prop_defs=(
            PropDef(
                key="socket_type",
                label="socket type",
                kind="readonly",
                default="",
                description="'server' or 'client' — set when the component is added and cannot be changed.",
            ),
            PropDef(
                key="host",
                label="host",
                kind="str",
                default="localhost",
                description="Server: address to bind (use 0.0.0.0 for all interfaces). Client: remote host to connect to.",
            ),
            PropDef(
                key="port",
                label="port",
                kind="int",
                default=8080,
                description="TCP port number (1–65535).",
            ),
            PropDef(
                key="encoding",
                label="encoding",
                kind="str",
                default="utf-8",
                description="Text encoding for send_text/on_receive_text. Raw bytes bypass this.",
            ),
            PropDef(
                key="timeout",
                label="timeout (s)",
                kind="float",
                default=5.0,
                description="Seconds before a connect or recv raises a timeout error.",
            ),
            PropDef(
                key="buffer_size",
                label="buffer size",
                kind="int",
                default=4096,
                description="recv() chunk size in bytes. Increase for large file transfers.",
            ),
            PropDef(
                key="auto_connect",
                label="auto connect",
                kind="bool",
                default=False,
                description="If True, start listening / connect automatically when the form loads.",
            ),
            # server-only — rendered conditionally in the Properties panel
            PropDef(
                key="max_clients",
                label="max clients",
                kind="int",
                default=5,
                description="[Server] Maximum number of simultaneous client connections.",
            ),
            PropDef(
                key="bind_address",
                label="bind address",
                kind="str",
                default="0.0.0.0",
                description="[Server] Network interface to bind to. 0.0.0.0 = all interfaces.",
            ),
            # client-only — rendered conditionally in the Properties panel
            PropDef(
                key="retry_on_fail",
                label="retry on fail",
                kind="bool",
                default=False,
                description="[Client] If True, automatically retry the connection after a failure.",
            ),
            PropDef(
                key="retry_interval",
                label="retry interval (s)",
                kind="float",
                default=3.0,
                description="[Client] Seconds to wait before retrying after a failed connection.",
            ),
        ),
        handler_defs=(
            # ── connectable — wire to widget events ──────────────────────────
            ComponentHandlerDef(
                id="toggle_connect",
                label="_toggle_connect",
                description="One-button toggle: starts/listens on first click, disconnects on second. Generates all socket setup code. Used by the scaffold.",
                has_connector=True,
                default_body="",
            ),
            ComponentHandlerDef(
                id="start",
                label="_start",
                description="[Server] Begin listening. Use instead of toggle_connect when you want separate Listen / Stop buttons.",
                has_connector=True,
                default_body="",
                applies_to_modes=("server",),
            ),
            ComponentHandlerDef(
                id="connect",
                label="_connect",
                description="[Client] Connect to the server. Use instead of toggle_connect when you want separate Connect / Disconnect buttons.",
                has_connector=True,
                default_body="",
                applies_to_modes=("client",),
            ),
            ComponentHandlerDef(
                id="disconnect",
                label="_disconnect",
                description="Close all connections and stop the socket. Wire to a button.",
                has_connector=True,
                default_body="",
            ),
            ComponentHandlerDef(
                id="send_text",
                label="_send_text",
                description="Send a UTF-8 string to connected peer(s). Call self._{id}_send_text(text) from your code.",
                has_connector=False,
                default_body="",
            ),
            ComponentHandlerDef(
                id="send_file",
                label="_send_file",
                description="Send raw bytes to connected peer(s). Call self._{id}_send_file(data) from your code.",
                has_connector=False,
                default_body="",
            ),
            ComponentHandlerDef(
                id="quick_send",
                label="_quick_send",
                description="Read text from the message Entry and send it. Generated by the Chat scaffold.",
                has_connector=False,
                default_body="",
            ),
            ComponentHandlerDef(
                id="pick_and_send_file",
                label="_pick_and_send_file",
                description="Open file picker and send the selected file. Generated by the File Transfer scaffold.",
                has_connector=False,
                default_body="",
            ),
            # ── callbacks — always generated as stubs ────────────────────────
            ComponentHandlerDef(
                id="on_connect",
                label="_on_connect",
                description="Fired when a connection is established. Server: receives (conn, addr). Client: no args.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="on_disconnect",
                label="_on_disconnect",
                description="Fired when a connection is closed.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="on_receive_text",
                label="_on_receive_text",
                description="Fired with decoded string data when text is received.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="on_receive_file",
                label="_on_receive_file",
                description="Fired with raw bytes when binary data is received (UnicodeDecodeError on text decode).",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="on_send_text",
                label="_on_send_text",
                description="Fired after a text send completes.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="on_send_file",
                label="_on_send_file",
                description="Fired after a file/bytes send completes.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="on_error",
                label="_on_error",
                description="Fired when any socket exception occurs. Receives the exception object.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
            ComponentHandlerDef(
                id="on_timeout",
                label="_on_timeout",
                description="Fired when a connect or recv times out.",
                has_connector=False,
                default_body="pass  # TODO",
            ),
        ),
    ),

}


# ── Helpers ───────────────────────────────────────────────────────────────────

def all_component_types() -> list[str]:
    """Return all registered component type keys in display order."""
    return list(COMPONENT_REGISTRY.keys())


def get_component_def(type_key: str) -> ComponentDef | None:
    return COMPONENT_REGISTRY.get(type_key)


def default_props(type_key: str) -> dict[str, Any]:
    """Return a fresh props dict with all defaults for a component type."""
    cdef = COMPONENT_REGISTRY.get(type_key)
    if not cdef:
        return {}
    return {p.key: p.default for p in cdef.prop_defs}
